version: "3"
# docker compose 由几个服务组成的
services:
  #indiviual service name
  mysql8:
    image: mysql:8.0.34
    restart: always
    command:  #启动mysql容器的预设命令
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:  #初始化脚本
      -  ./script/mysqlInit/:/docker-entrypoint-initdb.d/
    ports: #外部访问 用 13316
      - 13316:3306